# docker-compose.service.yml
# Service Geliştirme ortamı

networks:
  sentiric-net: { name: "${NETWORK_NAME:-sentiric-net}", driver: bridge }

# YENİ: Modelleri saklamak için kalıcı bir volume tanımlıyoruz
volumes:
  stt-model-cache:

services:
  # --- SES ORKESTRASYON KATMANI ---
  stt-service:
    build: { context: ../sentiric-stt-service }
    env_file: ["${ENV_FILE_PATH}"]
    volumes: [stt-model-cache:/root/.cache]
    ports: ["${STT_SERVICE_PORT:-5001}:5001"]
    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m