# docker-compose.service.yml
# Service Geliştirme ortamı

networks:
  sentiric-net: { name: "${NETWORK_NAME:-sentiric-net}", driver: bridge }

volumes:
  stt-model-cache:

services:
  # --- SES ORKESTRASYON KATMANI ---
  stt-service:
    build: { context: ../sentiric-stt-service }
    env_file: ["${ENV_FILE_PATH}"]
    volumes: [stt-model-cache:/root/.cache]
    ports: ["${STT_SERVICE_PORT:-5001}:5001"]
    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      # Model hazır olduğunda daha hızlı haberdar olalım
      interval: 10s
      # Yanıt için bekleme süresi
      timeout: 5s
      # Sağlıksız saymadan önce deneme sayısı
      retries: 5
      # --- EN KRİTİK DEĞİŞİKLİK ---
      # Konteynere başlaması ve büyük modeli indirmesi/yüklemesi için 10 dakika süre tanı.
      # Bu süre boyunca healthcheck başarısız olsa bile konteyner sağlıksız sayılmaz.
      start_period: 10m